'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.18408
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference2
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference2.SSOGUIDSoap")>  _
    Public Interface SSOGUIDSoap
        
        'CODEGEN: 命名空間 http://tempuri.org/ 的項目名稱  strGUID 未標示為 nillable，正在產生訊息合約
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetUId", ReplyAction:="*")>  _
        Function GetUId(ByVal request As ServiceReference2.GetUIdRequest) As ServiceReference2.GetUIdResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetUIdRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetUId", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference2.GetUIdRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference2.GetUIdRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetUIdRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public strGUID As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal strGUID As String)
            MyBase.New
            Me.strGUID = strGUID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetUIdResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetUIdResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference2.GetUIdResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference2.GetUIdResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetUIdResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetUIdResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetUIdResult As String)
            MyBase.New
            Me.GetUIdResult = GetUIdResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface SSOGUIDSoapChannel
        Inherits ServiceReference2.SSOGUIDSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SSOGUIDSoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference2.SSOGUIDSoap)
        Implements ServiceReference2.SSOGUIDSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference2_SSOGUIDSoap_GetUId(ByVal request As ServiceReference2.GetUIdRequest) As ServiceReference2.GetUIdResponse Implements ServiceReference2.SSOGUIDSoap.GetUId
            Return MyBase.Channel.GetUId(request)
        End Function
        
        Public Function GetUId(ByVal strGUID As String) As String
            Dim inValue As ServiceReference2.GetUIdRequest = New ServiceReference2.GetUIdRequest()
            inValue.Body = New ServiceReference2.GetUIdRequestBody()
            inValue.Body.strGUID = strGUID
            Dim retVal As ServiceReference2.GetUIdResponse = CType(Me,ServiceReference2.SSOGUIDSoap).GetUId(inValue)
            Return retVal.Body.GetUIdResult
        End Function
    End Class
End Namespace
